const STORAGE_KEY='qrak-projects-v1',SYNC_KEY='qrak-sync-code-v1';
const BLOCKED_PROJECTS=['azani','3d multiplayer football','together mobiles','together mobiles app'];
const SEED_PROJECTS=[
  {id:'seed-clover',name:'Clover Academy',category:'AI',status:'active',stack:'HTML, CSS, JavaScript, AI, Vercel',description:'KLB-focused AI education platform with study resources, quizzes, progress tracking and an AI tutor.',notes:'Major education project. Keep KLB alignment, quiz generation, weak-area analysis and teacher tools in scope.',github:'',live:'https://clover-education--jnrprince773.replit.app',pinned:true,createdAt:Date.now(),updatedAt:Date.now()},
  {id:'seed-aniverse',name:'AniVerse',category:'Web App',status:'active',stack:'HTML, CSS, JavaScript',description:'Anime social platform for profiles, uploads, comments, likes and sharing with a cyberpunk UI.',notes:'Long-term social platform project.',github:'',live:'',pinned:true,createdAt:Date.now(),updatedAt:Date.now()},
  {id:'seed-fontstudio',name:'Font Studio X',category:'Tool',status:'active',stack:'HTML, CSS, JavaScript',description:'Creative font utility with font exploration and Instagram username generation tools.',notes:'Keep the UI fast, simple and creator-focused.',github:'',live:'',pinned:false,createdAt:Date.now(),updatedAt:Date.now()},
  {id:'seed-discipline',name:'Discipline OS',category:'Tool',status:'active',stack:'HTML, CSS, JavaScript, LocalStorage',description:'Personal discipline and streak-tracking system with tasks, streaks and coach-style feedback.',notes:'Local-first productivity system.',github:'',live:'',pinned:false,createdAt:Date.now(),updatedAt:Date.now()},
  {id:'seed-pulse',name:'Pulse Music',category:'Mobile',status:'idea',stack:'JavaScript',description:'Music app concept focused on a polished listening experience.',notes:'Concept stage; define core differentiator before implementation.',github:'',live:'',pinned:false,createdAt:Date.now(),updatedAt:Date.now()},
  {id:'seed-navigator',name:'Public Transport Navigator',category:'Tool',status:'idea',stack:'JavaScript, Maps',description:'Public transport navigation concept for discovering routes and helping riders plan journeys.',notes:'Future mapping and route-planning project.',github:'',live:'',pinned:false,createdAt:Date.now(),updatedAt:Date.now()},
  {id:'seed-mh-analyzer',name:'Mental Health Analyzer',category:'AI',status:'idea',stack:'Python, AI',description:'Experimental concept for structured wellbeing analysis and supportive insights.',notes:'Keep any future implementation privacy-first and non-diagnostic.',github:'',live:'',pinned:false,createdAt:Date.now(),updatedAt:Date.now()},
  {id:'seed-vtuber',name:'VRoid / VTuber Lab',category:'Other',status:'idea',stack:'VRoid, 3D',description:'Experimental workspace for avatar, VTuber and character-creation ideas.',notes:'Collect experiments, visual concepts and reusable assets here.',github:'',live:'',pinned:false,createdAt:Date.now(),updatedAt:Date.now()},
  {id:'seed-senoai',name:'Senoai',category:'AI',status:'idea',stack:'AI',description:'Experimental AI project and prototype space.',notes:'Keep as a research/experimental project until the core use case is defined.',github:'',live:'',pinned:false,createdAt:Date.now(),updatedAt:Date.now()},
  {id:'seed-nery',name:'Nery',category:'AI',status:'idea',stack:'AI',description:'Experimental AI project and prototype space.',notes:'Prototype archive and future development space.',github:'',live:'',pinned:false,createdAt:Date.now(),updatedAt:Date.now()},
  {id:'seed-examprep',name:'ExamPrepMaster',category:'School',status:'completed',stack:'HTML, CSS, JavaScript',description:'Earlier education-focused exam preparation demo used for experimentation.',notes:'Archive/demo project. Useful as a reference for future education builds.',github:'',live:'',pinned:false,createdAt:Date.now(),updatedAt:Date.now()},
  {id:'seed-vanessa',name:'Vanessa Project',category:'Other',status:'completed',stack:'HTML, CSS, JavaScript',description:'Personal web project and collection of custom pages built as experiments.',notes:'Keep as a personal archive project.',github:'',live:'',pinned:false,createdAt:Date.now(),updatedAt:Date.now()},
  {id:'seed-glypha',name:'Glypha',category:'Tool',status:'idea',stack:'HTML, CSS, JavaScript',description:'Simple OS-style interface concept developed as a successor name for the earlier Nexora direction.',notes:'Focus on clean system UI and a strong identity.',github:'',live:'',pinned:false,createdAt:Date.now(),updatedAt:Date.now()}
];
const $=s=>document.querySelector(s);const $$=s=>[...document.querySelectorAll(s)];
let projects=load(),activeFilter='all',search='';
function isBlockedProject(p){const hay=[p?.name,p?.description,p?.category].filter(Boolean).join(' ').toLowerCase();return BLOCKED_PROJECTS.some(term=>hay.includes(term))}
function load(){try{const raw=localStorage.getItem(STORAGE_KEY);if(!raw){const seeded=SEED_PROJECTS.filter(p=>!isBlockedProject(p));localStorage.setItem(STORAGE_KEY,JSON.stringify(seeded));return seeded}const parsed=JSON.parse(raw);const cleaned=Array.isArray(parsed)?parsed.filter(p=>!isBlockedProject(p)):[];if(cleaned.length!==parsed.length)localStorage.setItem(STORAGE_KEY,JSON.stringify(cleaned));return cleaned}catch{const seeded=SEED_PROJECTS.filter(p=>!isBlockedProject(p));try{localStorage.setItem(STORAGE_KEY,JSON.stringify(seeded))}catch{}return seeded}}
function save(){projects=projects.filter(p=>!isBlockedProject(p));localStorage.setItem(STORAGE_KEY,JSON.stringify(projects));render()}
function esc(v=''){return String(v).replace(/[&<>\\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\\':'&#92;','"':'&quot;'}[c]))}
function visible(){return projects.filter(p=>(activeFilter==='all'||p.status===activeFilter)&&[p.name,p.category,p.stack,p.description,p.notes].join(' ').toLowerCase().includes(search.toLowerCase()))}
function render(){const list=visible();$('#projectCount').textContent=projects.length;$('#activeCount').textContent=projects.filter(p=>p.status==='active').length;$('#doneCount').textContent=projects.filter(p=>p.status==='completed').length;$('#favCount').textContent=projects.filter(p=>p.pinned).length;$('#resultCount').textContent=`${list.length} shown`;$('#emptyState').hidden=list.length>0||projects.length>0;$('#projectGrid').innerHTML=list.map(card).join('');updateAnalytics()}
function card(p){const stacks=(p.stack||'').split(',').map(x=>x.trim()).filter(Boolean).slice(0,6).map(x=>`<span>${esc(x)}</span>`).join('');return `<article class="project-card"><div class="project-top"><span class="status-pill status-${esc(p.status)}">${esc(p.status)}</span><div><span class="category-pill">${esc(p.category)}</span><button class="pin ${p.pinned?'active':''}" data-action="pin" data-id="${p.id}" aria-label="Pin project">★</button></div></div><h3>${esc(p.name)}</h3><p class="project-description">${esc(p.description||'No description yet.')}</p><div class="stack">${stacks||'<span>No stack added</span>'}</div><div class="project-footer"><div class="project-links">${p.github?`<a class="tiny-btn" href="${esc(p.github)}" target="_blank" rel="noopener">GitHub ↗</a>`:''}${p.live?`<a class="tiny-btn" href="${esc(p.live)}" target="_blank" rel="noopener">Live ↗</a>`:''}</div><div><button class="tiny-btn" data-action="edit" data-id="${p.id}">Edit</button><button class="tiny-btn" data-action="delete" data-id="${p.id}">Delete</button></div></div></article>`}
function updateAnalytics(){const done=projects.filter(p=>p.status==='completed').length,rate=projects.length?Math.round(done/projects.length*100):0,counts={};projects.forEach(p=>(p.stack||'').split(',').map(s=>s.trim()).filter(Boolean).forEach(s=>counts[s]=(counts[s]||0)+1));const top=Object.entries(counts).sort((a,b)=>b[1]-a[1])[0];$('#aProjects').textContent=projects.length;$('#aCompletion').textContent=`${rate}%`;$('#aStack').textContent=top?top[0]:'—'}
function openModal(id=null){const p=id?projects.find(x=>x.id===id):null;$('#modalTitle').textContent=p?'Edit project':'New project';$('#projectId').value=p?.id||'';$('#nameInput').value=p?.name||'';$('#categoryInput').value=p?.category||'Web App';$('#statusInput').value=p?.status||'active';$('#stackInput').value=p?.stack||'';$('#descriptionInput').value=p?.description||'';$('#notesInput').value=p?.notes||'';$('#githubInput').value=p?.github||'';$('#liveInput').value=p?.live||'';$('#modalBackdrop').hidden=false;setTimeout(()=>$('#nameInput').focus(),30)}
function closeModal(){$('#modalBackdrop').hidden=true}
function toast(msg){const el=$('#toast');el.textContent=msg;el.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>el.classList.remove('show'),2600)}
function randomBytes(n=32){return crypto.getRandomValues(new Uint8Array(n))}
function b64(bytes){let s='';bytes.forEach(x=>s+=String.fromCharCode(x));return btoa(s).replace(/\\+/g,'-').replace(/\\//g,'_').replace(/=+$/,'')}
function unb64(s){s=s.replace(/-/g,'+').replace(/_/g,'/');while(s.length%4)s+='=';const bin=atob(s);return Uint8Array.from(bin,c=>c.charCodeAt(0))}
async function sha256(bytes){return new Uint8Array(await crypto.subtle.digest('SHA-256',bytes))}
async function deriveKey(secret){const base=await crypto.subtle.importKey('raw',secret,'PBKDF2',false,['deriveKey']);return crypto.subtle.deriveKey({name:'PBKDF2',salt:new TextEncoder().encode('QRAK-v1'),iterations:120000,hash:'SHA-256'},base,{name:'AES-GCM',length:256},false,['encrypt','decrypt'])}
async function encryptVault(secret,data){const key=await deriveKey(secret),iv=randomBytes(12),cipher=new Uint8Array(await crypto.subtle.encrypt({name:'AES-GCM',iv},key,new TextEncoder().encode(JSON.stringify(data))));return {iv:b64(iv),data:b64(cipher)}}
async function decryptVault(secret,payload){const key=await deriveKey(secret),plain=await crypto.subtle.decrypt({name:'AES-GCM',iv:unb64(payload.iv)},key,unb64(payload.data));return JSON.parse(new TextDecoder().decode(plain))}
async function vaultId(secret){return b64(await sha256(secret))}
function getSyncCode(){return localStorage.getItem(SYNC_KEY)||''}
function showSync(){const code=getSyncCode();$('#syncCode').value=code;$('#syncBackdrop').hidden=false}
function generateSync(){const code=b64(randomBytes(32));localStorage.setItem(SYNC_KEY,code);$('#syncCode').value=code;toast('New sync code generated. Save it somewhere safe.')}
async function cloudRequest(method,body){const r=await fetch('/api/sync',{method,headers:{'content-type':'application/json'},body:JSON.stringify(body)});const data=await r.json().catch(()=>({}));if(!r.ok)throw new Error(data.error||'Cloud sync is not configured yet.');return data}
async function uploadCloud(){const code=getSyncCode();if(!code)return toast('Generate a sync code first.');try{const secret=unb64(code),payload=await encryptVault(secret,projects),id=await vaultId(secret);await cloudRequest('POST',{id,payload});$('#vaultStatus').innerHTML='<i></i> SYNCED';toast('Encrypted vault uploaded to QRAK Cloud.')}catch(e){toast(e.message)}}
async function restoreCloud(){const code=$('#syncCode').value.trim()||getSyncCode();if(!code)return toast('Enter or generate your sync code first.');try{const secret=unb64(code),id=await vaultId(secret),res=await cloudRequest('GET',{id});const restored=await decryptVault(secret,res.payload);if(!Array.isArray(restored))throw new Error('Invalid vault data.');projects=restored.filter(p=>!isBlockedProject(p));localStorage.setItem(STORAGE_KEY,JSON.stringify(projects));localStorage.setItem(SYNC_KEY,code);render();$('#vaultStatus').innerHTML='<i></i> SYNCED';toast(`Restored ${projects.length} projects from cloud.`)}catch(e){toast(e.message.includes('404')?'No cloud vault found for this code.':e.message)}}
$('#newProjectBtn')?.addEventListener('click',()=>openModal());$('#emptyCreateBtn')?.addEventListener('click',()=>openModal());$('#closeModal')?.addEventListener('click',closeModal);$('#cancelBtn')?.addEventListener('click',closeModal);$('#modalBackdrop')?.addEventListener('click',e=>{if(e.target.id==='modalBackdrop')closeModal()});
$('#projectForm')?.addEventListener('submit',e=>{e.preventDefault();const id=$('#projectId').value;const data={name:$('#nameInput').value.trim(),category:$('#categoryInput').value,status:$('#statusInput').value,stack:$('#stackInput').value.trim(),description:$('#descriptionInput').value.trim(),notes:$('#notesInput').value.trim(),github:$('#githubInput').value.trim(),live:$('#liveInput').value.trim()};if(isBlockedProject(data))return toast('That project has been permanently removed from QRAK.');if(id){const i=projects.findIndex(p=>p.id===id);projects[i]={...projects[i],...data,updatedAt:Date.now()}}else projects.unshift({id:crypto.randomUUID(),...data,pinned:false,createdAt:Date.now(),updatedAt:Date.now()});save();closeModal();toast('Project saved.')});
$('#projectGrid')?.addEventListener('click',e=>{const b=e.target.closest('[data-action]');if(!b)return;const p=projects.find(x=>x.id===b.dataset.id);if(!p)return;if(b.dataset.action==='edit')openModal(p.id);if(b.dataset.action==='pin'){p.pinned=!p.pinned;save();toast(p.pinned?'Project pinned.':'Project unpinned.')}if(b.dataset.action==='delete'&&confirm(`Delete ${p.name}?`)){projects=projects.filter(x=>x.id!==p.id);save();toast('Project deleted.')}});
$('#searchInput')?.addEventListener('input',e=>{search=e.target.value;render()});$$('.filter').forEach(b=>b.addEventListener('click',()=>{$$('.filter').forEach(x=>x.classList.remove('active'));b.classList.add('active');activeFilter=b.dataset.filter;render()}));
$('#exportBtn')?.addEventListener('click',()=>{const blob=new Blob([JSON.stringify({version:1,exportedAt:new Date().toISOString(),projects},null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='qrak-vault.json';a.click();URL.revokeObjectURL(a.href);toast('Vault exported.')});
$('#syncBtn')?.addEventListener('click',showSync);$('#heroSyncBtn')?.addEventListener('click',showSync);$('#closeSync')?.addEventListener('click',()=>$('#syncBackdrop').hidden=true);$('#syncBackdrop')?.addEventListener('click',e=>{if(e.target.id==='syncBackdrop')e.currentTarget.hidden=true});$('#generateSync')?.addEventListener('click',generateSync);$('#uploadSync')?.addEventListener('click',uploadCloud);$('#restoreSync')?.addEventListener('click',restoreCloud);$('#copySync')?.addEventListener('click',async()=>{if(!$('#syncCode').value)generateSync();await navigator.clipboard.writeText($('#syncCode').value);toast('Sync code copied.')});
$('#themeBtn')?.addEventListener('click',()=>{document.body.classList.toggle('high-contrast');const enabled=document.body.classList.contains('high-contrast');$('#themeBtn').textContent=enabled?'◑':'◐'});
const sections=[...document.querySelectorAll('main section[id]')],navLinks=[...document.querySelectorAll('.nav a')];window.addEventListener('scroll',()=>{const marker=scrollY+innerHeight*.3;let current=sections[0]?.id;sections.forEach(s=>{if(marker>=s.offsetTop)current=s.id});navLinks.forEach(l=>l.classList.toggle('active',l.getAttribute('href')===`#${current}`))},{passive:true});
if(getSyncCode())$('#vaultStatus').innerHTML='<i></i> SYNC READY';render();
